# ceerious i3 status config
# see "man i3status" for documentation.
#
# It is important that this file is edited as UTF-8.
# The following line should contain a sharp s:
# ß
# If the above line is not correctly displayed, fix your editor first!
###############################################################################

general {
    interval 		= 1
    colors 			= true
    color_good      = '#88b090'
    color_degraded  = '#ccdc90'
    color_bad       = '#e89393'
    separator = ''
}

order += "wireless wlp0s20f3"
order += "ethernet enp0s13f0u2u2"
order += "tztime local"
order += "battery 0"
order += "volume master"
order += "disk /"
#order += "disk /home"
#order += "run_watch DHCP"
#order += "ipv6"
#order += "run_watch VPN"
order += "cpu_temperature 0"
order += "cpu_usage 0"
order += "load"

wireless wlp0s20f3 {
    format_up = "     %essid %quality %ip    "
    format_down = "    down"
}

ethernet enp0s13f0u2u2 {
    #if you use %speed, i3status requires root privileges
    format_up = "ETH: %ip (%speed)    "
    format_down = "ETH: down"
}

battery 0 {
    format = "  %status %percentage %remaining  "
    format_down = ""
    last_full_capacity = true
    integer_battery_capacity = true
    low_threshold = 11
    threshold_type = percentage
    hide_seconds = true
    status_chr = " "
    status_bat = " "
    status_unk = " "
    status_full = " "
}

tztime local {
    format="%A %d %B %H:%M:%S - KW:%V   "
    timezone = "Europe/Berlin"
}

load {
    format = "    LOAD: 🖥  %1min  | %5min | %15min    "
}

cpu_usage {
    format = "   %usage  "
}

cpu_temperature 0 {
	format = "      CPU:    %degrees°C  |"
}

disk "/" {
	format = "    %avail"
	prefix_type	= custom
	low_threshold = 20
	threshold_type = percentage_avail
}

volume master {
    format = "  %volume  "
    format_muted = "  %volume "
    device = "default"
    mixer = "Master"
    mixer_idx = 0
}
